name: SQL Unit tests

on: [push, pull_request,repository_dispatch]

defaults:
  run:
    shell: bash

jobs:
  unitTests:
    name: SQL unit tests
    runs-on: ubuntu-latest
    env:
      GEN: ninja

    steps:
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v6

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Build Arrow extension
        run: make release

      - name: Run SQL unit tests
        run: make test